
name: dqn
# DQN algorithm hyperparameters
gamma: 0.99
lr: 1e-3
batch_size: 64
buffer_size: 100000
start_learning_after: 1000
target_update_every: 1000
tau: 1.0         # 1.0 -> hard update
eps_start: 1.0
eps_end: 0.05
eps_decay_steps: 50000
huber_delta: 1.0
clip_grad_norm: 10.0
