name: dqn
network:
  hidden1: 128
  hidden2: 64
optimizer:
  lr: 5e-4
  weight_decay: 1e-5
agent:
  gamma: 0.99
  tau: 0.005
  batch_size: 64
  buffer_capacity: 10000
  clip_grad_value: 5.0
  epsilon:
    start: 0.9
    end: 0.05
    decay_steps: 2000
